### ISSUE TITLE
agent-release

### ISSUE THREAD

**Issue by sumanblack666** [zzzteph/kraker#7]
After configured apps.settings.json ,i got the following error when i run the agent in windows . 
[16:13:26 INF] [inventory] Time to check inventory!
[16:13:26 INF] Build a command for hashcat:hashcat.exe -I
[16:13:26 INF] [inventory] Have detected a new fil?: C:\Users\Suman\Documents\Agent\rule\d3adhob0.rule
[16:13:26 INF] [inventory] Have detected a new fil?: C:\Users\Suman\Documents\Agent\rule\dive.rule
[16:13:26 INF] [inventory] Have detected a new fil?: C:\Users\Suman\Documents\Agent\rule\hob064.rule.txt
[16:13:26 INF] [inventory] Have detected a new fil?: C:\Users\Suman\Documents\Agent\rule\tmyst256.rule
[16:13:26 INF] [inventory] Have detected a new fil?: C:\Users\Suman\Documents\Agent\rule\tmyst32.rule
[16:13:26 INF] [inventory] Have detected a new fil?: C:\Users\Suman\Documents\Agent\rule\tmyst64.rule
[16:13:26 INF] [inventory] Have detected a new fil?: C:\Users\Suman\Documents\Agent\rule\ultra.rule
[16:13:26 INF] Hashcat out: hashcat (v6.1.1) starting...
[16:13:27 INF] Hashcat out:
[16:13:27 INF] [inventory] Have detected a new fil?: C:\Users\Suman\Documents\Agent\rule\_NSAKEY.v1.dive.rule
[16:13:27 INF] [inventory] Have detected a new fil?: C:\Users\Suman\Documents\Agent\wordlist\10_million_password_list_top_1000000.txt
[16:13:27 INF] [inventory] Have detected a new fil?: C:\Users\Suman\Documents\Agent\wordlist\english.txt
[16:13:27 INF] [inventory] Have detected a new fil?: C:\Users\Suman\Documents\Agent\wordlist\Names.dic
[16:13:27 INF] [inventory] Have detected a new fil?: C:\Users\Suman\Documents\Agent\wordlist\rockyou.txt
[16:13:27 INF] Hashcat out: * Device #1: CUDA SDK Toolkit installation NOT detected.
[16:13:27 INF] Hashcat out:              CUDA SDK Toolkit installation required for proper device support and utilization
[16:13:27 INF] Hashcat out:              Falling back to OpenCL Runtime
[16:13:27 INF] Hashcat out:
[16:13:28 INF] Hashcat out: OpenCL Info:
[16:13:28 INF] Hashcat out: ============
[16:13:28 INF] Hashcat out:
[16:13:28 INF] Hashcat out: OpenCL Platform ID #1
[16:13:28 INF] Hashcat out:   Vendor..: NVIDIA Corporation
[16:13:28 INF] Hashcat out:   Name....: NVIDIA CUDA
[16:13:28 INF] Hashcat out:   Version.: OpenCL 1.2 CUDA 10.1.131
[16:13:28 INF] Hashcat out:
[16:13:28 INF] Hashcat out:   Backend Device ID #1
[16:13:28 INF] Hashcat out:     Type...........: GPU
[16:13:28 INF] Hashcat out:     Vendor.ID......: 32
[16:13:28 INF] Hashcat out:     Vendor.........: NVIDIA Corporation
[16:13:28 INF] Hashcat out:     Name...........: GeForce GT 750M
[16:13:28 INF] Hashcat out:     Version........: OpenCL 1.2 CUDA
[16:13:28 INF] Hashcat out:     Processor(s)...: 2
[16:13:28 INF] Hashcat out:     Clock..........: 967
[16:13:28 INF] Hashcat out:     Memory.Total...: 2048 MB (limited to 512 MB allocatable in one block)
[16:13:28 INF] Hashcat out:     Memory.Free....: 1664 MB
[16:13:28 INF] Hashcat out:     OpenCL.Version.: OpenCL C 1.2
[16:13:28 INF] Hashcat out:     Driver.Version.: 425.31
[16:13:28 INF] Hashcat out:
[16:13:28 INF] Hashcat out: OpenCL Platform ID #2
[16:13:28 INF] Hashcat out:   Vendor..: Intel(R) Corporation
[16:13:28 INF] Hashcat out:   Name....: Intel(R) OpenCL
[16:13:28 INF] Hashcat out:   Version.: OpenCL 1.2
[16:13:28 INF] Hashcat out:
[16:13:28 INF] Hashcat out:   Backend Device ID #2
[16:13:28 INF] Hashcat out:     Type...........: GPU
[16:13:28 INF] Hashcat out:     Vendor.ID......: 8
[16:13:28 INF] Hashcat out:     Vendor.........: Intel(R) Corporation
[16:13:28 INF] Hashcat out:     Name...........: Intel(R) HD Graphics 4600
[16:13:28 INF] Hashcat out:     Version........: OpenCL 1.2
[16:13:28 INF] Hashcat out:     Processor(s)...: 20
[16:13:28 INF] Hashcat out:     Clock..........: 1200
[16:13:28 INF] Hashcat out:     Memory.Total...: 1629 MB (limited to 407 MB allocatable in one block)
[16:13:28 INF] Hashcat out:     Memory.Free....: 1565 MB
[16:13:28 INF] Hashcat out:     OpenCL.Version.: OpenCL C 1.2
[16:13:28 INF] Hashcat out:     Driver.Version.: 20.19.15.4568
[16:13:28 INF] Hashcat out:
[16:13:28 INF] Hashcat out:   Backend Device ID #3
[16:13:28 INF] Hashcat out:     Type...........: CPU
[16:13:28 INF] Hashcat out:     Vendor.ID......: 8
[16:13:28 INF] Hashcat out:     Vendor.........: Intel(R) Corporation
[16:13:28 INF] Hashcat out:     Name...........: Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz
[16:13:28 INF] Hashcat out:     Version........: OpenCL 1.2 (Build 10094)
[16:13:28 INF] Hashcat out:     Processor(s)...: 8
[16:13:28 INF] Hashcat out:     Clock..........: 3100
[16:13:28 INF] Hashcat out:     Memory.Total...: 16309 MB (limited to 4077 MB allocatable in one block)
[16:13:28 INF] Hashcat out:     Memory.Free....: 16245 MB
[16:13:28 INF] Hashcat out:     OpenCL.Version.: OpenCL C 1.2
[16:13:28 INF] Hashcat out:     Driver.Version.: 5.2.0.10094
[16:13:28 INF] Hashcat out:
[16:13:28 INF] Build a command for hashcat:hashcat.exe -V
[16:13:28 INF] Hashcat out: v6.1.1
[16:13:28 INF] [inventory] Changes've detected, save data
[16:13:28 ERR] Got an exception while checking inventory: System.InvalidOperationException: The agent needs to have id
   at Kracker.Base.Domain.Inventory.InventoryManager.GetAgentId() in F:\develop\kraker\agent\Kracker.Base\Domain\Inventory\InventoryManager.cs:line 70
   at Kracker.Base.Domain.Inventory.InventoryManager.UpdateFileDescriptions() in F:\develop\kraker\agent\Kracker.Base\Domain\Inventory\InventoryManager.cs:line 113
   at Kracker.App.Program.<>c__DisplayClass4_0.<<InitializeCheckInventoryTimer>b__0>d.MoveNext() in F:\develop\kraker\agent\Kracker.App\Program.cs:line 59
Unhandled exception. Refit.ApiException: An error occured deserializing the response.
 ---> System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 6 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 6 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Refit.SystemTextJsonContentSerializer.FromHttpContentAsync[T](HttpContent content, CancellationToken cancellationToken) in /_/Refit/SystemTextJsonContentSerializer.cs:line 63
   at Refit.RequestBuilderImplementation.DeserializeContentAsync[T](HttpResponseMessage resp, HttpContent content, CancellationToken cancellationToken) in /_/Refit/RequestBuilderImplementation.cs:line 324
   --- End of inner exception stack trace ---
   at Refit.RequestBuilderImplementation.DeserializeContentAsync[T](HttpResponseMessage resp, HttpContent content, CancellationToken cancellationToken) in /_/Refit/RequestBuilderImplementation.cs:line 330
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 277
--- End of stack trace from previous location ---
   at Kracker.Base.Domain.AgentRegistrationManager.Register() in F:\develop\kraker\agent\Kracker.Base\Domain\AgentRegistrationManager.cs:line 44
   at Kracker.Base.Startup.PrepareAgent() in F:\develop\kraker\agent\Kracker.Base\Startup.cs:line 42
   at Kracker.App.Program.Work(ILogger logger, Config config, IStartup startup, IAgentInfoProvider agentInfoProvider) in F:\develop\kraker\agent\Kracker.App\Program.cs:line 76
   at Kracker.App.Program.Main(String[] args) in F:\develop\kraker\agent\Kracker.App\Program.cs:line 42
   at Kracker.App.Program.<Main>(String[] args)

**Comment by narutyona** [comment]
Hi! Can you share your appsettings.json file, please?

**Comment by sumanblack666** [comment]
Hi..Here is my setting .I even tried to build using dotnet but still unable to connect to server .


{
	"HashCat":{
		"Path": "hashcat-6.1.1\\hashcat.exe",
		"SilencePeriodBeforeKill": 5, //default - 60 minutes
		"RepeatedStringsBeforeKill": 100, //defaut 1000 strings
		"NeedForce": true,
		"Options": "--quiet --status --status-timer=1 --machine-readable --logfile-disable --restore-disable --outfile-format=2"
	},
	"ServerUrl": "http://202.186.177.180",
	"InventoryCheckPeriod": 600,
	"HearbeatPeriod": 15	
}

**Comment by zzzteph** [comment]
@sumanblack666 It seems the agent could not connect to the server, or the server was not installed properly.

**Comment by sumanblack666** [comment]
Yeah.. Managed to solve this. 10q
